### ISSUE TITLE
Default Content Width and Height

### ISSUE THREAD

**Issue by miukimiu** [yusinto/react-site-nav#5]
Hello,

Thank you for this awesome component!

I'm wondering in case we have the following situation:
```
<ContentGroup title="About">
    <a href="#">Link C</a>
    <a href="#">Link D</a>
</ContentGroup>
```
See example here:
https://codesandbox.io/s/rlz4q3x2zp

Shouldn't this situation by default get the` defaultContentWidth` and `defaultContentHeight`?

I wanted to open a PR for this but I noticed that you have a comment saying: 

```
// if width and height are not specified, that means we don't want to render the content group i.e. we only
// want to render root item
``` 

So I'm not sure what this is intended to do. What do you mean by root item?

```
  memoizeMenuData = memoize((columnWidth, children) => React.Children.map(children, (child, i) => {
    // if width and height are not specified, that means we don't want to render the content group i.e. we only
    // want to render root item
    const {width, height} = child.props;
    let sanitisedWidth, sanitisedHeight;

    if (!width && !height) {
      sanitisedWidth = 0;
      sanitisedHeight = 0;
    } else {
      // if width or height is not specified, add defaults
      sanitisedWidth = width || defaultContentWidth;
      sanitisedHeight = height || defaultContentHeight;
    }
```

Also is it possible to have a link without a ContentGroup?

```
 <SiteNav>
    <a href="#">I'm a link without a ContentGroup</a>
    <ContentGroup title="About">
      <a href="#">Link B</a>
      <a href="#">Link C</a>
    </ContentGroup>
    <ContentGroup title="Contact" width="420" height="270">
      <a href="#">Link D</a>
      <a href="#">Link E</a>
    </ContentGroup>
  </SiteNav>
``` 

Thanks!

**Comment by yusinto** [comment]
@miukimiu hi there, I've updated the code recently and I didn't update the readme so apologies.
 
A root item is the grid item representing the "title" prop of a ContentGroup. See the screenshot below.
<img width="917" alt="rootitems" src="https://user-images.githubusercontent.com/1593077/45572675-533a9000-b8ad-11e8-87d0-88b3d2deeb19.png">

To have a link root item without a content group, you can do this:
```jsx
<ContentGroup title="Some Link" rootUrl="https://to/somewhere" />
```
That's the reason why a content group width and height is set to 0 if both are unspecified. The site nav assumes you don't want a content group. Check my [blog](https://reactjunkie.com/) for a demo of a link without a content group.

I'll update the documentation to reflect this information. Let me know if this works!

**Comment by miukimiu** [comment]
Yes, it works! Thank you!! 😄
